apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  namespace: default
  labels:
    run: nginx
    type: webserver
spec:
  containers:
  - name: mynginx
    image: nginx:latest
    ports:
    - containerPort: 80